config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :suppliers
  resources :parts_includeds
  resources :issues

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'

  resources :included_parts
  resources :suppliers
  resources :invoices
  resources :parts
  resources :employees
  resources :cars
  resources :customers
  resources :home
  resources :customers do
  member do
    get :showcar
  end
end
  resources :cars do
  member do
    get :showinvoice
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

end

app/models/customer.rb
class Customer < ApplicationRecord
	
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/included_part.rb
class IncludedPart < ApplicationRecord
  belongs_to :part
  belongs_to :inv
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :cust
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :part
  belongs_to :supp
end

app/models/parts_included.rb
class PartsIncluded < ApplicationRecord
  belongs_to :part
  belongs_to :inv
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:showinvoice, :show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  def showinvoice
  end
  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:car_vin, :car_model, :car_make, :car_year, :cust_id, :license_plate)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:emp_id, :emp_fname, :emp_lname, :emp_wage)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end
	

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :emp_id %>
    <%= form.text_field :emp_id, id: :employee_emp_id %>
  </div>

  <div class="field">
    <%= form.label :emp_fname %>
    <%= form.text_field :emp_fname, id: :employee_emp_fname %>
  </div>

  <div class="field">
    <%= form.label :emp_lname %>
    <%= form.text_field :emp_lname, id: :employee_emp_lname %>
  </div>

  <div class="field">
    <%= form.label :emp_wage %>
    <%= form.text_field :emp_wage, id: :employee_emp_wage %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<style>
th, td{
  padding-left: 20px;
}
</style>

<p id="notice"><%= notice %></p>

<h1 style="text-align:center">Employees</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Hourly Wage</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.emp_id %></td>
        <td><%= employee.emp_fname %></td>
        <td><%= employee.emp_lname %></td>
        <td><%= employee.emp_wage %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path, class: "btn btn-primary" %>
<%= link_to 'Home', home_index_path, class: "btn btn-primary" %>

app/views/employees/new.html.erb
<h1 style="padding-left:100px">New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path%>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp id:</strong>
  <%= @employee.emp_id %>
</p>

<p>
  <strong>Emp fname:</strong>
  <%= @employee.emp_fname %>
</p>

<p>
  <strong>Emp lname:</strong>
  <%= @employee.emp_lname %>
</p>

<p>
  <strong>Emp wage:</strong>
  <%= @employee.emp_wage %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>