config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :suppliers
  resources :parts_includeds
  resources :issues

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'

  resources :included_parts
  resources :suppliers
  resources :invoices
  resources :parts
  resources :employees
  resources :cars
  resources :customers
  resources :home
  resources :customers do
  member do
    get :showcar
  end
end
  resources :cars do
  member do
    get :showinvoice
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

end

app/models/customer.rb
class Customer < ApplicationRecord
	
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/included_part.rb
class IncludedPart < ApplicationRecord
  belongs_to :part
  belongs_to :inv
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :cust
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :part
  belongs_to :supp
end

app/models/parts_included.rb
class PartsIncluded < ApplicationRecord
  belongs_to :part
  belongs_to :inv
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:showinvoice, :show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  def showinvoice
  end
  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:car_vin, :car_model, :car_make, :car_year, :cust_id, :license_plate)
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:inv_id, :cost_of_labor, :car_vin, :cust_id, :emp_id, :inv_desc, :prob_desc, :eng_code, :inv_date, :tot_cost)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end
	

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/invoices/_form.html.erb
<%= form_with(model: invoice, local: true) do |form| %>
  <% if invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :cost_of_labor, 'Cost Of Labor', class: "col-md-2 control-label" %>
    <%= form.text_field :cost_of_labor, id: :invoice_cost_of_labor %>
  </div>

  <div class="form-group">
    <%= form.label :car_vin, 'VIN', class: "col-md-2 control-label" %>
    <% vin = params[:car_vin] %>
    <%= form.text_field :car_vin, id: :invoice_car_vin, value: vin %>
  </div>

  <div class="form-group">
    <%= form.label :cust_id, 'Customer ID', class: "col-md-2 control-label" %>
    <% id = params[:cust_id] %>
    <%= form.text_field :cust_id, id: :invoice_cust_id, value: id %>
  </div>

  <div class="form-group">
    <%= form.label :emp_id, 'Employee ID', class: "col-md-2 control-label" %>
    <%= form.text_field :emp_id, id: :invoice_emp_id %>
  </div>

  <div class="form-group">
    <%= form.label :inv_desc, 'Work Done', class: "col-md-2 control-label" %>
    <%= form.text_field :inv_desc, id: :invoice_inv_desc %>
  </div>

  <div class="form-group">
    <%= form.label :prob_desc, 'Problem Description', class: "col-md-2 control-label" %>
    <%= form.text_field :prob_desc, id: :invoice_prob_desc %>
  </div>

  <div class="form-group">
    <%= form.label :eng_code, 'Engine Code', class: "col-md-2 control-label" %>
    <%= form.text_field :eng_code, id: :invoice_eng_code %>
  </div>

  <div class="form-group">
    <%= form.label :inv_date, 'Invoice Date', class: "col-md-2 control-label" %>
    <%= form.date_select :inv_date, id: :invoice_inv_date %>
  </div>

  <div class="form-group">
    <%= form.label :tot_cost, 'Total Cost', class: "col-md-2 control-label" %>
    <%= form.text_field :tot_cost, id: :invoice_tot_cost %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit',  class: "btn btn-primary col-md-2"%>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Edit Invoice</h1>

<%= render 'form', invoice: @invoice %>


<% cust = params[:cust_id] %>
<%customer = Customer.find(cust) %>
</br></br>
<%= link_to 'Back', showcar_customer_path(customer), class: "btn btn-default" %>

app/views/invoices/index.html.erb
<style>
th, td{
  padding-left: 20px;
}
</style>

<p id="notice"><%= notice %></p>

<h1 style="text-align:center">Invoices</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Cost of labor</th>
      <th>Vin #</th>
      <th>Customer ID</th>
      <th>Employee ID</th>
      <th>Work Done</th>
      <th>Description of Problem</th>
      <th>Engine code</th>
      <th>Invoice date</th>
      <th>Total cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.cost_of_labor %></td>
        <td><%= invoice.car_vin %></td>
        <td><%= invoice.cust_id %></td>
        <td><%= invoice.emp_id %></td>
        <td><%= invoice.inv_desc %></td>
        <td><%= invoice.prob_desc %></td>
        <td><%= invoice.eng_code %></td>
        <td><%= invoice.inv_date %></td>
        <td><%= invoice.tot_cost %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path, class: "btn btn-primary" %>

app/views/invoices/new.html.erb
<h1 style="padding-left:120px">New Invoice</h1>

<%= render 'form', invoice: @invoice %>

<%= link_to 'Back', invoices_path, class: "btn btn-default col-md-2" %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cost of labor:</strong>
  <%= @invoice.cost_of_labor %>
</p>

<p>
  <strong>Car vin:</strong>
  <%= @invoice.car_vin %>
</p>

<p>
  <strong>Cust:</strong>
  <%= @invoice.cust_id %>
</p>

<p>
  <strong>Emp:</strong>
  <%= @invoice.emp_id %>
</p>

<p>
  <strong>Inv desc:</strong>
  <%= @invoice.inv_desc %>
</p>

<p>
  <strong>Prob desc:</strong>
  <%= @invoice.prob_desc %>
</p>

<p>
  <strong>Eng code:</strong>
  <%= @invoice.eng_code %>
</p>

<p>
  <strong>Inv date:</strong>
  <%= @invoice.inv_date %>
</p>

<p>
  <strong>Tot cost:</strong>
  <%= @invoice.tot_cost %>
</p>
<% @customer = Customer.find(@invoice.cust_id) %>
<%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn btn-default" %>
<%= link_to 'Back', showcar_customer_path(@customer), class: "btn btn-default"%>