config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :suppliers
  resources :parts_includeds
  resources :issues

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'

  resources :included_parts
  resources :suppliers
  resources :invoices
  resources :parts
  resources :employees
  resources :cars
  resources :customers
  resources :home
  resources :customers do
  member do
    get :showcar
  end
end
  resources :cars do
  member do
    get :showinvoice
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

end

app/models/customer.rb
class Customer < ApplicationRecord
	
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/included_part.rb
class IncludedPart < ApplicationRecord
  belongs_to :part
  belongs_to :inv
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :cust
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :part
  belongs_to :supp
end

app/models/parts_included.rb
class PartsIncluded < ApplicationRecord
  belongs_to :part
  belongs_to :inv
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:showinvoice, :show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  def showinvoice
  end
  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:car_vin, :car_model, :car_make, :car_year, :cust_id, :license_plate)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy, :showcar]

  # GET /customers
  # GET /customers.json
  def index
    @customers = if params[:cust_phone]
      Customer.where('cust_phone LIKE ?' , "%#{params[:cust_phone]}%")
    else
      Customer.all
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end
  # GET /customers/1/showcar
  def showcar
  end
    



  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:cust_id, :cust_fname, :cust_lname, :cust_phone, :cust_addr, :cust_date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end
	

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form-group">
    <% id = Customer.all %>
    <%= form.label :cust_id, 'Customer ID', class: "col-md-2 control-label" %>
    <%= form.text_field :cust_id, id: :customer_cust_id, value: id.count + 1, :readonly => true %>
  </div>


  <div class="form-group">
    <%= form.label :cust_fname, 'First Name', class: "col-md-2 control-label" %>
    <%= form.text_field :cust_fname, id: :customer_cust_fname %>
  </div>

  <div class="form-group">
    <%= form.label :cust_lname,'Last Name', class: "col-md-2 control-label"  %>
    <%= form.text_field :cust_lname, id: :customer_cust_lname %>
  </div>

  <div class="form-group">
    <%= form.label :cust_phone,'Phone Number', class: "col-md-2 control-label"  %>
    <%= form.text_field :cust_phone, id: :customer_cust_phone %>
  </div>

  <div class="form-group">
    <%= form.label :cust_addr,'Address', class: "col-md-2 control-label"  %>
    <%= form.text_field :cust_addr, id: :customer_cust_addr %>
  </div>

  <div class="form-group">
    <%= form.label :cust_date, 'Date Registered', class: "col-md-2 control-label"  %>
    <%= form.date_select :cust_date, id: :customer_cust_date %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-primary col-md-2" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render 'form', customer: @customer %>
</br></br>

<%= link_to 'Back', customers_path, class: "btn btn-default" %>

app/views/customers/index.html.erb
<style>
th, td{
  padding-left: 20px;
}
</style>

<p id="notice"><%= notice %></p>

<h1 style="text-align:center">Customers</h1>

  <%= form_tag customers_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :cust_phone %>
    <%= submit_tag "Search" %>
  </p>
<% end %>

<table class="table table-striped table-bordered">

  <thead>
    <tr>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Date</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.cust_id %></td>
        <td><%= customer.cust_fname %></td>
        <td><%= customer.cust_lname %></td>
        <td><%= customer.cust_phone %></td>
        <td><%= customer.cust_addr %></td>
        <td><%= customer.cust_date %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <td><%= link_to 'New Car', new_car_path(customer, :cust_id => customer.cust_id) %></td>
        <td><%= link_to 'Show Cars', showcar_customer_path(customer) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path, class: "btn btn-primary" %>
<%= link_to 'Home', home_index_path, class: "btn btn-primary" %>

app/views/customers/new.html.erb
<h1 style="padding-left:100px">New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path, class: "btn btn-default col-md-2" %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>ID</strong>
  <%= @customer.cust_id %>
</p>

<p>
  <strong>First Name:</strong>
  <%= @customer.cust_fname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @customer.cust_lname %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @customer.cust_phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.cust_addr %>
</p>

<p>
  <strong>Date Registered:</strong>
  <%= @customer.cust_date %>
</p>

<%= link_to 'Add Car', new_car_path(@customer, :cust_id => @customer.cust_id), class: "btn btn-primary" %>
<%= link_to 'Edit', edit_customer_path(@customer), class: "btn btn-default" %>
<%= link_to 'Home', home_index_path, class: "btn btn-default" %>

app/views/customers/showcar.html.erb
<style>
th, td{
  padding-left: 20px;
}
</style>

<p id="notice"><%= notice %></p>

<h1 style="text-align:center">Cars</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Customer</th>
      <th>License plate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% @belongstocust = Car.where(cust_id: @customer.cust_id) %>
    <% @belongstocust.each do |car| %>
      <tr>
        <td><%= car.car_make %></td>
        <td><%= car.car_model %></td>
        <td><%= car.car_year %></td>
        <td><%= @customer.cust_fname%> <%= @customer.cust_lname%></td>
        <td><%= car.license_plate %></td>
        <td><%= link_to 'Create New Invoice', new_invoice_path(@invoice, :cust_id => car.cust_id, :car_vin => car.car_vin) %>
        <td><%= link_to 'View Invoices', showinvoice_car_path(:id=> car.car_vin) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'Back', customers_path, class: "btn btn-primary" %>
<br>