config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users
  resources :suppliers
  resources :parts_includeds
  resources :issues

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'home#index'

  resources :included_parts
  resources :suppliers
  resources :invoices
  resources :parts
  resources :employees
  resources :cars
  resources :customers
  resources :home
  resources :customers do
  member do
    get :showcar
  end
end
  resources :cars do
  member do
    get :showinvoice
  end
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

end

app/models/customer.rb
class Customer < ApplicationRecord
	
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/included_part.rb
class IncludedPart < ApplicationRecord
  belongs_to :part
  belongs_to :inv
end

app/models/invoice.rb
class Invoice < ApplicationRecord
	
end

app/models/issue.rb
class Issue < ApplicationRecord
  belongs_to :cust
end

app/models/part.rb
class Part < ApplicationRecord
  belongs_to :part
  belongs_to :supp
end

app/models/parts_included.rb
class PartsIncluded < ApplicationRecord
  belongs_to :part
  belongs_to :inv
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:showinvoice, :show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  def showinvoice
  end
  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:car_vin, :car_model, :car_make, :car_year, :cust_id, :license_plate)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end
	

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :car_vin, 'VIN',  class: "col-md-2 control-label" %>
    <%= form.text_field :car_vin, id: :car_car_vin %>
  </div>

  <div class="form-group">
    <%= form.label :car_make, 'Make',  class: "col-md-2 control-label" %>
    <%= form.text_field :car_make, id: :car_car_make %>
  </div>

  <div class="form-group">
    <%= form.label :car_model, "Model", class: "col-md-2 control-label" %>
    <%= form.text_field :car_model, id: :car_car_model %>
  </div>

  <div class="form-group">
    <%= form.label :car_year, 'Year', class: "col-md-2 control-label" %>
    <%= form.text_field :car_year, id: :car_car_year %>
  </div>

  <div class="form-group">
    <% id = params[:cust_id] %>
    <%= form.label :cust_id, 'Customer ID', class: "col-md-2 control-label" %>
    <%= form.text_field :cust_id, id: :car_cust_id, value: id %>
  </div>

  <div class="form-group">
    <%= form.label :license_plate, 'License Plate', class: "col-md-2 control-label" %>
    <%= form.text_field :license_plate, id: :car_license_plate %>
  </div>

  <div class="form-group">
    <%= form.submit 'Submit',  class: "btn btn-primary col-md-2" %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= render 'form', car: @car %>
</br></br>
<%= link_to 'Back', cars_path, class: "btn btn-default" %>

app/views/cars/index.html.erb
<style>
th, td{
  padding-left: 20px;
}
</style>

<p id="notice"><%= notice %></p>

<h1 style="text-align:center">Cars</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>VIN</th>
      <th>Make</th>
      <th>Model</th>
      <th>Year</th>
      <th>Customer ID</th>
      <th>License Plate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%=car.car_vin %></td>
        <td><%= car.car_make %></td>
        <td><%= car.car_model %></td>
        <td><%= car.car_year %></td>
        <td><%= car.cust_id %></td>
        <td><%= car.license_plate %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <% if current_user.admin? %>
        <td><%= link_to 'Destroy', @car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_car_path, class: "btn btn-primary" %>
<%= link_to 'Home', home_index_path, class: "btn btn-primary" %>

app/views/cars/new.html.erb
<h1 style="padding-left:130px">New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', customers_path, class: "btn btn-default col-md-2" %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Car model:</strong>
  <%= @car.car_model %>
</p>

<p>
  <strong>Car make:</strong>
  <%= @car.car_make %>
</p>

<p>
  <strong>Car year:</strong>
  <%= @car.car_year %>
</p>

<p>
  <strong>Cust id:</strong>
  <%= @car.cust_id %>
</p>

<p>
  <strong>License plate:</strong>
  <%= @car.license_plate %>
</p>
<% @customer = Customer.find(@car.cust_id) %>
<%= link_to 'Edit', edit_car_path(@car), class: "btn btn-default" %>
<%= link_to 'Back', showcar_customer_path(@customer), class: "btn btn-default" %>

app/views/cars/showinvoice.html.erb
<style>
th, td{
  padding-left: 20px;
}
</style>

<p id="notice"><%= notice %></p>

<h1 style="text-align:center">Invoices</h1>

<table  class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Car VIN</th>
      <th>Cost of Labor</th>
      <th>Customer ID</th>
      <th>Employee ID</th>
      <th>Work Done</th>
      <th>Problem Description</th>
      <th>Engine Code</th>
      <th>Invoice Date</th>
      <th>Total Cost</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  	<% @invoices = Invoice.where(car_vin: @car.car_vin) %>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.car_vin %></td>
        <td><%= invoice.cost_of_labor %></td>
        <td><%= invoice.cust_id %></td>
        <td><%= invoice.emp_id %></td>
        <td><%= invoice.inv_desc %></td>
        <td><%= invoice.prob_desc %></td>
        <td><%= invoice.eng_code %></td>
        <td><%= invoice.inv_date %></td>
        <td><%= invoice.tot_cost %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice, cust_id: invoice.cust_id, car_vin: invoice.car_vin) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% @customer = Customer.find(@car.cust_id) %>
<%= link_to 'Back', showcar_customer_path(@customer), class: "btn btn-primary" %>